blank_issues_enabled: false
contact_links:
  - name: 📋 GitHub Discussions
    url: https://github.com/Talus-Network/.github/discussions
    about: Start here for feature ideas, questions, and community discussion
  - name: 🔒 Security Issues
    url: https://github.com/Talus-Network/.github/security/advisories/new
    about: Report security vulnerabilities privately (never use public issues)
  - name: 💬 Community Support
    url: https://discord.gg/talus
    about: Get help from the community on Discord
  - name: 📖 Documentation
    url: https://docs.talus.network
    about: Check our documentation for guides and API references
